import { Pet } from './types';
import bellaImage from './assets/images/bella_corgi_dog_1779681395245.png';
import oliverImage from './assets/images/oliver_siamese_cat_1779681933203.png';

export const PETS_DATA: Pet[] = [
  {
    id: '1',
    name: 'Milo',
    species: 'dog',
    breed: '米克斯',
    age: '2 歲',
    gender: 'Male',
    image: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=800&q=80',
    description: 'Milo 個性穩定，喜歡散步，也能安靜待在室內。牠需要每天固定活動，適合願意花時間陪伴的家庭。',
    traits: ['親人', '會坐下', '適合公寓', '散步穩定'],
    vaccinated: true,
    size: 'Medium',
    location: '台北市',
  },
  {
    id: '2',
    name: 'Bella',
    species: 'dog',
    breed: '柯基',
    age: '1 歲',
    gender: 'Female',
    image: bellaImage,
    description: 'Bella 活潑親人，對新環境適應快。因為年紀還小，需要家人持續陪牠練習基本規矩。',
    traits: ['活潑', '親人', '需耐心訓練', '可與小型犬相處'],
    vaccinated: true,
    size: 'Small',
    location: '新北市',
  },
  {
    id: '3',
    name: 'Luna',
    species: 'cat',
    breed: '玳瑁貓',
    age: '1 歲',
    gender: 'Female',
    image: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=800&q=80',
    description: 'Luna 剛開始會觀察環境，熟悉後會主動靠近。適合安靜、願意給貓咪時間的家庭。',
    traits: ['慢熟', '安靜', '親貓', '喜歡窗邊'],
    vaccinated: true,
    size: 'Small',
    location: '台中市',
  },
  {
    id: '4',
    name: 'Oliver',
    species: 'cat',
    breed: '暹羅貓',
    age: '4 個月',
    gender: 'Male',
    image: oliverImage,
    description: 'Oliver 是好奇心很強的小貓，喜歡玩逗貓棒。幼貓需要較多陪伴，也需要安全的室內空間。',
    traits: ['幼貓', '好奇', '愛玩', '需室內飼養'],
    vaccinated: false,
    size: 'Small',
    location: '台北市',
  },
  {
    id: '5',
    name: 'Finn',
    species: 'dog',
    breed: '拉布拉多混種',
    age: '3 歲',
    gender: 'Male',
    image: 'https://images.unsplash.com/photo-1531804055935-76f44d7c3621?auto=format&fit=crop&w=800&q=80',
    description: 'Finn 很喜歡人，也喜歡戶外活動。牠體型較大，適合有穩定作息、能每天帶牠運動的家庭。',
    traits: ['親人', '需要運動', '會牽繩', '不適合久關籠'],
    vaccinated: true,
    size: 'Large',
    location: '桃園市',
  },
  {
    id: '6',
    name: 'Cleo',
    species: 'cat',
    breed: '虎斑貓',
    age: '8 個月',
    gender: 'Female',
    image: 'https://images.unsplash.com/photo-1573865526739-10659fec78a5?auto=format&fit=crop&w=800&q=80',
    description: 'Cleo 親人但不黏人，喜歡乾淨的貓砂盆和固定作息。適合第一次養貓但願意做功課的人。',
    traits: ['親人', '愛乾淨', '適合新手', '室內貓'],
    vaccinated: true,
    size: 'Small',
    location: '新竹市',
  },
  {
    id: '7',
    name: 'Mocha',
    species: 'dog',
    breed: '臘腸混種',
    age: '10 個月',
    gender: 'Male',
    image: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&w=800&q=80',
    description: 'Mocha 對熟人很熱情，對陌生聲音有點敏感。需要願意慢慢建立安全感的照顧者。',
    traits: ['親熟人', '需安全感', '小型犬', '可練習獨處'],
    vaccinated: true,
    size: 'Small',
    location: '台南市',
  },
  {
    id: '8',
    name: 'Coco',
    species: 'cat',
    breed: '橘白貓',
    age: '2 歲',
    gender: 'Female',
    image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=800&q=80',
    description: 'Coco 已經習慣室內生活，個性穩定。牠喜歡被摸頭，但不喜歡被抱太久。',
    traits: ['穩定', '親人', '不愛被抱', '適合公寓'],
    vaccinated: true,
    size: 'Medium',
    location: '高雄市',
  },
  {
    id: '9',
    name: 'Lucky',
    species: 'dog',
    breed: '米克斯',
    age: '1.5 歲',
    gender: 'Male',
    image: 'https://images.unsplash.com/photo-1583511655826-05700d52f4d9?auto=format&fit=crop&w=800&q=80',
    description: 'Lucky 曾經流浪，現在已經學會信任人。牠需要穩定環境，不建議頻繁搬家或長時間獨處。',
    traits: ['穩定中', '親人', '需陪伴', '適合有經驗者'],
    vaccinated: true,
    size: 'Medium',
    location: '彰化縣',
  },
  {
    id: '10',
    name: 'Simba',
    species: 'cat',
    breed: '長毛混種',
    age: '3 歲',
    gender: 'Male',
    image: 'https://images.unsplash.com/photo-1533738363-b7f9aef128ce?auto=format&fit=crop&w=800&q=80',
    description: 'Simba 個性沉穩，需要定期梳毛。牠適合安靜家庭，也適合想找成熟貓咪陪伴的人。',
    traits: ['沉穩', '需梳毛', '安靜', '成熟貓'],
    vaccinated: true,
    size: 'Medium',
    location: '台中市',
  },
];
