import { Pet } from './types';
import bellaImage from './assets/images/bella_corgi_dog_1779681395245.png';
import oliverImage from './assets/images/oliver_siamese_cat_1779681933203.png';

export const PETS_DATA: Pet[] = [
  {
    id: '1',
    name: 'Milo',
    species: 'dog',
    breed: '黃金獵犬',
    age: '2 歲',
    gender: 'Male',
    image: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=600&q=80',
    description: 'Milo 是一隻非常快樂、充滿活力的黃金獵犬。他最喜歡玩接網球、游泳和在戶外玩抓人遊戲。他與小朋友和其他寵物都相處得非常好！',
    traits: ['親人友善', '已學會定點排泄', '活力充沛', '對小孩友善'],
    vaccinated: true,
    size: 'Large',
    location: '台北市'
  },
  {
    id: '2',
    name: 'Bella',
    species: 'dog',
    breed: '彭布羅克威爾斯柯基犬',
    age: '1 歲',
    gender: 'Female',
    image: bellaImage,
    description: 'Bella 是一隻非常溫柔、貼心的柯基犬。她最喜歡摸摸肚子、散散步，並睡在最愛的主人身邊。她非常聰明，能快速學會新把戲。',
    traits: ['聰明伶俐', '撒嬌黏人', '活潑好動', '愛說話'],
    vaccinated: true,
    size: 'Small',
    location: '新北市'
  },
  {
    id: '3',
    name: 'Luna',
    species: 'cat',
    breed: '米克斯橘貓',
    age: '1 歲',
    gender: 'Female',
    image: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=600&q=80',
    description: 'Luna 是一隻充滿好奇心的橘貓，最喜歡追逐雷射筆，或躺在窗邊曬太陽。她很愛撒嬌，喜歡被摸頭，還會發出超療癒的呼嚕聲。',
    traits: ['好奇心旺盛', '親人貼心', '愛玩', '愛撒嬌'],
    vaccinated: true,
    size: 'Medium',
    location: '台中市'
  },
  {
    id: '4',
    name: 'Oliver',
    species: 'cat',
    breed: '暹羅貓',
    age: '4 個月',
    gender: 'Male',
    image: oliverImage,
    description: 'Oliver 是一隻擁有迷人藍眼睛的幼年暹羅貓。他非常親人，喜歡爬貓跳台，而且能在溫暖的膝蓋上不出一秒鐘就沉沉入睡。',
    traits: ['愛玩好動', '大腿暖包', '極度親人', '喜歡互動'],
    vaccinated: false,
    size: 'Small',
    location: '高雄市'
  },
  {
    id: '5',
    name: 'Finn',
    species: 'dog',
    breed: '西伯利亞哈士奇',
    age: '3 歲',
    gender: 'Male',
    image: 'https://images.unsplash.com/photo-1531804055935-76f44d7c3621?auto=format&fit=crop&w=600&q=80',
    description: 'Finn 是一隻外表帥氣但個性極度反差萌且溫柔的哈士奇。他活動量大，非常喜歡登山和跑步，喜歡涼爽的天氣，表情超級豐富！',
    traits: ['運動神經發達', '表情包大師', '忠心耿耿', '愛碎碎念'],
    vaccinated: true,
    size: 'Large',
    location: '宜蘭縣'
  },
  {
    id: '6',
    name: 'Cleo',
    species: 'cat',
    breed: '米克斯虎斑貓',
    age: '8 個月',
    gender: 'Female',
    image: 'https://images.unsplash.com/photo-1573865526739-10659fec78a5?auto=format&fit=crop&w=600&q=80',
    description: 'Cleo 是一隻活潑的虎斑幼貓，最喜歡狩獵玩具滑鼠。只要聽到零食包裝的聲音就會超級興奮，還喜歡在棉被底下玩躲貓貓。',
    traits: ['愛玩活潑', '獨立自主', '好奇心強'],
    vaccinated: true,
    size: 'Small',
    location: '台南市'
  },
  {
    id: '7',
    name: 'Mocha (摩卡)',
    species: 'dog',
    breed: '玩具貴賓犬',
    age: '10 個月',
    gender: 'Male',
    image: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&w=600&q=80',
    description: 'Mocha 是一隻超級貼心的玩具貴賓犬。他個性極度溫柔、不亂吠叫，最喜歡在人懷裡撒嬌睡覺。期待溫暖且有耐心的家庭帶他回家！',
    traits: ['極度貼心', '溫柔乖巧', '親人粘人', '不亂吠叫'],
    vaccinated: true,
    size: 'Small',
    location: '彰化縣'
  },
  {
    id: '8',
    name: 'Coco',
    species: 'cat',
    breed: '英國短毛貓',
    age: '2 歲',
    gender: 'Female',
    image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=600&q=80',
    description: 'Coco 是一隻胖嘟嘟的英短。她的臉圓滾滾的，脾氣超級好，可以像布偶一樣被抱在懷裡。最喜歡的就是吃好吃的罐罐和睡下午覺。',
    traits: ['性格溫順', '親人可抱', '貪吃鬼'],
    vaccinated: true,
    size: 'Medium',
    location: '台北市'
  },
  {
    id: '9',
    name: 'Lucky',
    species: 'dog',
    breed: '台灣犬',
    age: '1.5 歲',
    gender: 'Male',
    image: 'https://images.unsplash.com/photo-1583511655826-05700d52f4d9?auto=format&fit=crop&w=600&q=80',
    description: 'Lucky 是一隻非常忠心的台灣犬黑狗。他的警覺性高、認主且極度聰明。對於新事物稍微害羞，但只要建立信任，他會是你一輩子最忠誠的守護者。',
    traits: ['忠心護主', '敏捷靈巧', '聰明警覺'],
    vaccinated: true,
    size: 'Large',
    location: '桃園市'
  },
  {
    id: '10',
    name: 'Simba',
    species: 'cat',
    breed: '緬因貓',
    age: '3 歲',
    gender: 'Male',
    image: 'https://images.unsplash.com/photo-1533738363-b7f9aef128ce?auto=format&fit=crop&w=600&q=80',
    description: 'Simba 是一隻體型巨大的緬因貓。他有著漂亮的鬃毛與蓬鬆的大尾巴，性格溫和優雅，被稱為「溫和的巨人」。喜歡與人對話，發出細小的鳴叫聲。',
    traits: ['溫和巨人', '喜歡對話', '毛髮蓬鬆', '親人友善'],
    vaccinated: true,
    size: 'Large',
    location: '台中市'
  },
  {
    id: '11',
    name: 'Mimi',
    species: 'cat',
    breed: '波斯貓',
    age: '2.5 歲',
    gender: 'Female',
    image: 'https://images.unsplash.com/photo-1592194996308-7b43878e84a6?auto=format&fit=crop&w=600&q=80',
    description: 'Mimi 是一隻高雅安靜的波斯貓。她不愛吵鬧，喜歡靜靜地看著窗外，偶爾會主動走過來靠著主人的腿撒嬌。適合安靜舒適的精緻生活環境。',
    traits: ['極度安靜', '氣質高雅', '不愛被打擾'],
    vaccinated: true,
    size: 'Medium',
    location: '高雄市'
  },
  {
    id: '12',
    name: 'Rocky',
    species: 'dog',
    breed: '柴犬',
    age: '1.2 歲',
    gender: 'Male',
    image: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=600&q=80',
    description: 'Rocky 是一隻有著完美微笑的可愛赤柴！他個性有些小固執，但是非常愛玩飛盤。對主人的忠誠度高，每次主人下班都會熱烈地搖尾巴歡迎。',
    traits: ['有個性', '柴犬微笑', '活力十足'],
    vaccinated: true,
    size: 'Medium',
    location: '新竹市'
  },
  {
    id: '13',
    name: 'Cookie',
    species: 'dog',
    breed: '邊境牧羊犬',
    age: '2 歲',
    gender: 'Female',
    image: 'https://images.unsplash.com/photo-1503256207526-0d5d80fa2f47?auto=format&fit=crop&w=600&q=80',
    description: 'Cookie 是接球與敏捷遊戲的天才！她智商極高，需要足夠的運動量與智力遊戲。如果你喜歡帶狗狗出去運動、訓練，那 Cookie 會是你的最佳拍檔。',
    traits: ['智商一流', '精力無極限', '極度熱愛球球'],
    vaccinated: true,
    size: 'Medium',
    location: '花蓮縣'
  },
  {
    id: '14',
    name: 'Teddy',
    species: 'dog',
    breed: '拉布拉多犬',
    age: '3 歲',
    gender: 'Male',
    image: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?auto=format&fit=crop&w=600&q=80',
    description: 'Teddy 有著陽光般的笑容和極好、極穩重的脾氣。他是一隻受過基礎訓練的拉布拉多，非常乖巧懂事，不撲人也不護食。對所有人都非常親切。',
    traits: ['暖男代表', '脾氣極好', '聽懂指令', '熱愛美食'],
    vaccinated: true,
    size: 'Large',
    location: '新北市'
  },
  {
    id: '15',
    name: 'Lily',
    species: 'cat',
    breed: '布偶貓',
    age: '1 歲',
    gender: 'Female',
    image: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=600&q=80',
    description: 'Lily 是美得像童話故事走出來的布偶貓。當你抱起她時，她就像布偶一樣軟綿綿地攤在你的懷裡。她叫聲細緻甜美，非常黏人，喜歡寸步不離跟著主人。',
    traits: ['仙女布偶', '軟萌可抱', '叫聲甜美', '跟屁蟲'],
    vaccinated: true,
    size: 'Medium',
    location: '台北市'
  }
];
